spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug